app/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length
from flask_babel import lazy_gettext as _l

class MessageForm(FlaskForm):
    message = TextAreaField(_l('Message'), validators=[DataRequired(),
                                                      Length(min=0, max=140)])
    submit = SubmitField(_l('Send'))


class MessageReplyForm(FlaskForm):
    reply = TextAreaField(_l('Send Message'), validators=[DataRequired(),
                                                   Length(min=0, max=140)])
    send = SubmitField(_l('Send'))

app/messages/__init__.py
from flask import Blueprint

bp = Blueprint('messages', __name__)

from app.messages import routes

app/messages/routes.py
from flask import (render_template, redirect, request, jsonify,
                   current_app, flash, url_for)
from flask_login import current_user, login_required
from datetime import time, datetime
from app import db
from app.messages import bp
from app.models import User, Message, Notification
from app.messages.forms import MessageForm, MessageReplyForm
from flask_babel import _


@bp.route('/send_message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    user = User.query.filter_by(username=recipient).first_or_404()
    form = MessageForm()
    if form.validate_on_submit():
        msg = Message(sender=current_user, recipient=user,
                      body=form.message.data)
        db.session.add(msg)
        user.add_notification('unread_message_count', user.new_messages())
        db.session.commit()
        flash(_('Your message has been sent.'))
        return redirect(url_for('main.user', username=recipient))
    return render_template('messages/send_message.html', title=_('Send Message'),
                           form=form, recipient=recipient)


@bp.route('/messages')
@login_required
def messages():
    current_user.last_message_read_time = datetime.utcnow()
    current_user.add_notification('unread_message_count', 0)
    db.session.commit()
    page = request.args.get('page', 1, type=int)

    messages_received = current_user.messages_received
    messages_sent = current_user.messages_sent

    pagination = current_app.config['MESSAGES_PER_PAGE']
    msg_pg = messages_received.union(messages_sent).order_by(
        Message.timestamp.desc()).paginate(
            page, pagination, False)

    pair = []
    recipients = []
    senders = []
    messages = []
    for message in msg_pg.items:
        sender = message.sender.username
        recipient = message.recipient.username

        users = [sender, recipient]
        users.sort()
        if users not in pair:
            messages.append(message)
            pair.append(users)

    next_url = None
    prev_url = None

    if msg_pg.next_num and len(messages) > pagination:
        next_url = url_for('messages.messages', page=msg_pg.next_num)
    if msg_pg.prev_num and len(messages) > pagination:
        prev_url = url_for('messages.messages', page=msg_pg.prev_num)

    return render_template('messages/messages.html', messages=messages,
                           next_url=next_url, prev_url=prev_url,
                           title=_('Messages'))

@bp.route('/user_messages/<username>', methods=['GET', 'POST'])
@login_required
def user_messages(username):

    form = MessageReplyForm()
    user = User.query.filter_by(username=username).first_or_404()

    if form.validate_on_submit():
        msg = Message(sender=current_user, recipient=user,
                        body=form.reply.data)
        db.session.add(msg)
        user.add_notification('unread_message_count', user.new_messages())
        db.session.commit()
        return redirect(url_for('messages.user_messages', username=username))

    page = request.args.get('page', 1, type=int)

    messages_received = current_user.messages_received.filter_by(sender=user)
    messages_sent = current_user.messages_sent.filter_by(recipient=user)

    messages = messages_received.union(messages_sent).order_by(
        Message.timestamp.desc()).paginate(
            page, current_app.config['MESSAGES_PER_PAGE'], False)

    for m in messages.items:
        if m.recipient == current_user:
            m.set_status(1)
    db.session.commit()

    next_url = url_for('messages.user_messages', username=username,
                       page=messages.next_num) if messages.has_next else None
    prev_url = url_for('messages.user_messages', username=username,
                       page=messages.prev_num) if messages.has_prev else None

    return render_template('messages/user_messages.html', messages=messages.items,
                           next_url=next_url, prev_url=prev_url, user=user,
                           form=form, title=_('User Messages'))

@bp.route('/notifications')
@login_required
def notifications():
    since = request.args.get('since', 0.0, type=float)
    notifications = current_user.notifications.filter(
        Notification.timestamp > since).order_by(
            Notification.timestamp.asc())

    return jsonify([{
        'name': n.name,
        'data': n.get_data(),
        'timestamp': n.timestamp
    } for n in notifications])

app/templates/_pagination.html
<nav aria-label="...">
    <ul class="pager">
        <li class="previous{% if not prev_url %} disabled{% endif %}">
            <a href="{{ prev_url or '#' }}">
                <span aria-aria-hidden="true">&larr;</span>{{ _('Newer') }}
            </a>
        </li>
        <li class="next{% if not next_url %} disabled{% endif %}">
            <a href="{{ next_url or '#' }}">
                {{ _('Older') }} <span aria-hidden="true">&rarr;</span>
            </a>
        </li>
    </ul>
</nav>

app/templates/_post.html
<table class="table table-hover">
    <tr>
        <td width="70px">
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                <img src="{{ post.author.avatar(70) }}" alt="">
            </a>
        </td>
        <td>
            {% set user_link %}
                <span class="user_popup">
                    <a href="{{ url_for('main.user', username=post.author.username) }}">
                        {% if post.author == current_user %}
                            {{ _('You') }}
                        {% else %}
                            {{ post.author.username }}
                        {% endif %}
                    </a>
                </span>
            {% endset %}
            {{ _('%(username)s said %(when)s', username=user_link,
            when=moment(post.timestamp).fromNow()) }}:<br>
            {{ post.body }}
        </td>
    </tr>
</table>

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
    {% if title %}{{ title }} - Paphrablog
    {% else %}Welcome to Microblog
    {% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" name="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1"
                        aria-expanded='false'>
                    <span class="sr-only">{{ _('Toggle navigation') }}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">
                    Paphrablog</a>
            </div>
            <div class="collapse navbar-collapse"
                 id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">
                        {{ _('Home') }}</a></li>
                    <li><a href="{{ url_for('main.explore') }}">
                        {{ _('Explore') }}</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">
                        {{ _('Login') }}</a></li>
                    {% else %}
                    <li><a href="{{ url_for('messages.messages') }}">
                            {{ _('Messages') }}
                            {% set new_messages = current_user.new_messages() %}
                            {% if new_messages %}
                            <span id="message_count" class="badge"
                                style="visibility: {% if new_messages %}visible{% endif %}">
                                {{ new_messages }}</span>
                            {% endif %}
                       </a></li>
                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">
                        {{ _('Profile') }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">
                        {{ _('Logout') }}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-info" role="alert">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang(g.locale) }}

    <script>
        $(function() {
            var timer = null;
            var xhr = null;
            $('.user_popup').hover(
                function(event) {
                    // mouse in even handler
                    var elem = $(event.currentTarget);
                    function display(data) {
                        xhr = null;
                        elem.popover({
                            trigger: 'manual',
                            html: true,
                            animation: false,
                            container: elem,
                            content: data
                        }).popover('show');
                        flask_moment_render_all();
                    }
                    function load() {
                        timer = null;
                        xhr = $.ajax(
                            '/user/' + elem.first().text().trim() + '/popup'
                        ).done(display);
                    }
                    timer = setTimeout(load, 1000);
                },
                function(event) {
                    // mouse out even handler
                    var elem = $(event.currentTarget);
                    if (timer) {
                        clearTimeout(timer);
                        time = null;
                    }
                    else if(xhr) {
                        xhr.abort();
                        xhr = null;
                    }
                    else {
                        elem.popover('destroy');
                    }
                }
            )
        });

        function set_message_count(n){
            $('#message_count').text(n);
            $('#message_count').css('visibility', n ? 'visible' : 'hidden');
        }

        {% if current_user.is_authenticated %}
        $(function(){
            var since = 0;
            function make(notifications){
                for (var i=0; i<notifications.length; i++){
                    if (notifications[i].name == 'unread_message_count'){
                        set_message_count(notifications[i].data);
                        since = notifications[i].timestamp;
                    }
                }
            }
            function send(){
                $.ajax(
                    "{{ url_for('messages.notifications') }}?since=" + since
                ).done(make);
            }
            setInterval(send, 10000);
        });
        {% endif %}
    </script>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h3 style="text-align: center;">Edit Profile</h3>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h3 style="text-align: center;">
        {{ _('Hi, %(username)s!', username=current_user.username) }}</h3>

    {% if form %}
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    {% endif %}

    {% for post in posts %}
        {% include "_post.html" %}
    {% endfor %}
    {% include "_pagination.html" %}
{% endblock %}

app/templates/messages.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ _('Messages') }}</h1>
    {% for post in messages %}
        {% include '_post.html' %}
    {% endfor %}

    {% include "_pagination.html" %}
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block app_content %}
    <table class="table table-hover">
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}" alt=""></td>
            <td>
                <h3 class="" style="text-align: center;">{{ _('User: %(username)s', username=user.username) }}</h3>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                    <p>{{ _('Last Seen on: %(when)s',
                        when=moment(user.last_seen).format('LLL')) }}</p>
                {% endif %}
                <p>{{ _('%(followers)s followers,',
                    followers=user.followers.count()) }}
                    {{ _('%(following)s following.',
                    following=user.followed.count()) }}</p>

                {% if user == current_user %}
                <p><a href="{{ url_for('main.edit_profile') }}">
                    {{ _('Edit your Profile') }}</a></p>
                {% elif not current_user.is_following(user) %}
                <p><a href="{{ url_for('main.follow', username=user.username) }}">
                    {{ _('Follow') }}</a></p>
                {% else %}
                <p><a
                    href="{{ url_for('main.unfollow', username=user.username) }}">
                    {{ _('Unfollow') }}</a></p>
                {% endif %}
                {% if user != current_user %}
                <p>
                    <a href="{{ url_for('messages.user_messages', username=user.username) }}">
                    {{ _('Send private message') }}</a>
                </p>
                {% endif %}
            </td>
        </tr>
    </table>
    <hr>
    {% for post in posts %}
        {% include "_post.html" %}
    {% endfor %}
    {% include "_pagination.html" %}
{% endblock %}

app/templates/user_popup.html
<table class="table">
    <tr>
        <td width="64" style="border: 0px;">
            <img src="{{ user.avatar(64) }}" alt="">
        </td>
        <td style="border: 0px;">
            <p>
                <a href="{{ url_for('main.user', username=user.username) }}">
                    {{ user.username }}
                </a>
            </p>
            <small>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                <p>{{ _('Last Seen on') }}:
                   {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                <p>{{ _('%(count)d followers', count=user.followers.count()) }},
                    {{ _('%(count)d following', count=user.followed.count()) }}
                </p>
                {% if user != current_user %}
                    {% if not current_user.is_following(user) %}
                    <a href="{{ url_for('main.follow', username=user.username) }}">
                        {{ _('Follow') }}</a>
                    {% else %}
                    <a href="{{ url_for('main.unfollow', username=user.username) }}">
                        {{ _('Unfollow') }}</a>
                    {% endif %}
                {% endif %}
            </small>
        </td>
    </tr>
</table>